version: "3.7"
services:
    rabbitMQ:
        image: rabbitmq:3.8-rc-management
        environment:
            - RABBITMQ_DEFAULT_PASS=rmqpass
            - RABBITMQ_DEFAULT_USER=rmquser
        ports:
            - "5672:5672"
            - "15672:15672"
