version: "3.7"
services:
    pg:
        image: postgres:10-alpine
        environment:
            - POSTGRES_PASSWORD=dbpass
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        ports:
            - "5432:5432"
